services:
  app:
    build: .
    restart: on-failure
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/game_service_db
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:19092
    networks:
      - default
      - chesstracker

networks:
  chesstracker:
    external: true
